accounts:
  - name: Alex
    coins: ["20000terp", "200000000stash"]
  - name: Austin
    coins: ["10000terp", "100000000stash"]
validator:
  name: Alex
  staked: "100000000terps"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: Austin
  coins: ["5terps", "10000stash"]
  #host:
  # rpc:  ":26659"
  # p2p:  ":26655"
  # prof:  ":6060"
  # grpc:  ":9090"
  # api:  ":1318"
genesis:
  chain_id: "morocco-1"
  app_state:
    staking:
      params:
        bond_denom: "terp"
    mint:
      params:
        mint_denom: "stash"
    crisis:
      constant_fee:
        denom: "stash"
    gov:
      deposit_params:
          min_deposit:
            amount: "5000"
            denom: "terp"
  